apiVersion: v1
kind: Service
metadata:
  name: {{ include "greenie-mvp-frontend.serviceAccountName" . }}
  labels: {{- include "greenie-mvp-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "greenie-mvp-frontend.selectorLabels" . | nindent 4 }}
