apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenie-mvp-frontend-dev
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: greenie-frontend
          image: ghcr.io/greenie-one/frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
